// Importing Components
import TermsAndConditions from "./DocumentSection/Documents/TermsAndConditions";
import ManduCoinsPolicy from "./DocumentSection/Documents/ManduCoinsPolicy";
import OpenSourceContributionGuidelines from "./DocumentSection/Documents/OpenSourceContributionGuidelines";
import AgeRestrictionsPolicy from "./DocumentSection/Documents/AgeRestrictionsPolicy";
import FeedbackAndReporting from "./DocumentSection/Documents/FeedbackAndReporting";
import PrivacyPolicy from "./DocumentSection/Documents/PrivacyPolicy";
import GuffManduBetaRelease from "./DocumentSection/Documents/GuffManduBetaRelease";

// Importing the route
import { createLegalAndPoliciesRoute } from "@Utilities/frontendRoutes"

/**
 * Function to create an item object with title, link, section, and component.
 * The link is automatically generated by converting the title to lowercase,
 * replacing spaces with hyphens, and passing it to the route creation utility.
 * 
 * @param {string} title - The title of the legal or policy item.
 * @param {React.Component} Component - The component to render for the document section.
 * @returns {Object} - The object representing the item with title, link, and component properties.
 */
const createItem = (title, Component) => {
    return {
        title, // The title of the legal/policy item
        link: createLegalAndPoliciesRoute(title.toLowerCase().replace(/\s+/g, "-")), // Automatically creates a link by formatting the title
        component: Component // The component that should be rendered in the document section
    }
}

/**
 * The main array holding all the legal and policy items. Each item is created using the createItem function.
 * The link is automatically generated by the function based on the title.
 * The component for each item is passed as a second argument to createItem.
 */
const legalAndPoliciesItems = [
    createItem("GuffMandu Beta Release", GuffManduBetaRelease),
    createItem("Terms and Conditions", TermsAndConditions),
    createItem("Mandu Coins Policy", ManduCoinsPolicy),
    createItem("Open Source Contribution Guidelines", OpenSourceContributionGuidelines),
    createItem("Feedback and Reporting", FeedbackAndReporting),
    createItem("Age Restriction", AgeRestrictionsPolicy),
    createItem("Privacy Policy", PrivacyPolicy),
];

// Exporting the items to be used in other parts of the application (e.g., Sidebar and DocumentSections)
export default legalAndPoliciesItems;